name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3 # Use the appropriate Go version

      - name: Build and Deploy
        run: |
          cd backend
          go build -o kingkush
          ./kingkush & # Start your Golang server
